[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/zzet"
  weight = 40
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  name = "X"
  url = "https://x.com/zzetorg"
  weight = 50
  [main.params]
    icon = "x-twitter"
    showName = false
    target = "_blank"


[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search" 

[[footer]]
  name = "Archive"
  pageRef = "archive"
  weight = 20